from __future__ import annotations

import logging
import re
import shutil
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from pypdf import PdfReader

from config import Settings, get_settings

LOGGER = logging.getLogger(__name__)


class DocumentWashError(RuntimeError):
    """Raised when a document cannot be converted or cleaned safely."""


class UnsupportedDocumentError(DocumentWashError):
    """Raised when the document format is not supported by the washer."""


@dataclass(slots=True)
class WashedDocument:
    source_path: Path
    raw_markdown: str
    clean_markdown: str
    used_ocr: bool
    notes: list[str] = field(default_factory=list)


class DocumentWasher:
    TOC_HEADING_PATTERN = re.compile(
        r"^(?:#{1,6}\s*)?(?:table of contents|contents|toc|目录)$",
        re.IGNORECASE,
    )
    TOC_ENTRY_PATTERN = re.compile(
        r"^(?:[-*]\s+)?(?:\d+(?:\.\d+)*\s+)?[^\n]{4,}?(?:\.{3,}|…{2,}|-{3,}|_{3,})\s*\d+\s*$"
    )
    METADSample_PATTERN = re.compile(
        r"(?i)^(author|authors|producer|created|creation date|last modified|modified|updated|source|generated by|captured by|printed on)\s*[:|-]"
    )
    PAGE_PATTERN = re.compile(r"(?i)^page\s+\d+(?:\s+of\s+\d+)?$")
    SLIDE_PATTERN = re.compile(r"(?i)^slide\s+\d+(?:\s+of\s+\d+)?$")

    def __init__(self, settings: Settings | None = None) -> None:
        self.settings = settings or get_settings()
        self._compiled_noise_patterns = [
            re.compile(pattern) for pattern in self.settings.NOISE_PATTERNS
        ]
        self._converter = None

    def wash(self, file_path: str | Path) -> WashedDocument:
        path = Path(file_path).expanduser().resolve()
        suffix = path.suffix.lower()

        if path.stat().st_size == 0:
            raise DocumentWashError(f"Input document is empty: {path.name}")

        if suffix in {".md", ".txt", ".csv"}:
            raw_markdown = path.read_text(encoding="utf-8", errors="ignore")
            used_ocr = False
            notes = ["plain-text passthrough"]
        elif suffix == ".pdf" and not self.settings.OCR_ENABLED:
            raw_markdown = self._extract_pdf_text_fallback(path)
            used_ocr = False
            notes = ["pdf text fallback because OCR is disabled"]
        elif suffix in {
            ".pdf",
            ".pptx",
            ".docx",
            ".xlsx",
            ".html",
            ".htm",
            ".png",
            ".jpg",
            ".jpeg",
            ".tif",
            ".tiff",
            ".bmp",
        }:
            used_ocr = suffix == ".pdf" and self.settings.OCR_ENABLED
            notes = ["docling conversion"]
            try:
                raw_markdown = self._convert_with_docling(path)
            except DocumentWashError:
                if suffix != ".pdf" or not self.settings.PDF_TEXT_FALLBACK_ENABLED:
                    raise
                raw_markdown = self._extract_pdf_text_fallback(path)
                used_ocr = False
                notes = ["pdf text fallback after docling failure"]
            if used_ocr:
                notes.append("ocr enabled for image-heavy pages")
        elif suffix == ".ppt":
            raw_markdown = self._convert_legacy_ppt(path)
            used_ocr = False
            notes = [
                "legacy ppt converted to pptx via external office converter",
                "docling conversion",
            ]
        else:
            raise UnsupportedDocumentError(f"Unsupported document type: {suffix}")

        clean_markdown = self.clean_content(raw_markdown)
        if not clean_markdown.strip():
            raise DocumentWashError(f"Document became empty after cleaning: {path}")

        return WashedDocument(
            source_path=path,
            raw_markdown=raw_markdown,
            clean_markdown=clean_markdown,
            used_ocr=used_ocr,
            notes=notes,
        )

    def clean_content(self, raw_markdown: str) -> str:
        normalized_markdown = self._strip_invalid_surrogates(raw_markdown)
        lines = normalized_markdown.replace("\r\n", "\n").replace("\r", "\n").split("\n")
        cleaned_lines: list[str] = []
        in_toc_block = False
        toc_streak = 0

        for line in lines:
            stripped = line.strip()

            if not stripped:
                if cleaned_lines and cleaned_lines[-1] != "":
                    cleaned_lines.append("")
                continue

            if self.TOC_HEADING_PATTERN.fullmatch(stripped):
                in_toc_block = True
                toc_streak = 0
                continue

            if self._looks_like_toc_entry(stripped):
                toc_streak += 1
                if in_toc_block or toc_streak >= 2:
                    in_toc_block = True
                    continue
            else:
                toc_streak = 0

            if in_toc_block:
                if self._starts_body_content(stripped):
                    in_toc_block = False
                else:
                    continue

            if self._is_metadata_fragment(stripped):
                continue

            if any(pattern.search(stripped) for pattern in self._compiled_noise_patterns):
                continue

            if self._is_navigation_fragment(stripped):
                continue

            cleaned_lines.append(line.rstrip())

        cleaned_markdown = "\n".join(cleaned_lines)
        cleaned_markdown = re.sub(r"\n{3,}", "\n\n", cleaned_markdown).strip()
        return cleaned_markdown

    @staticmethod
    def _strip_invalid_surrogates(value: str) -> str:
        return value.encode("utf-8", errors="ignore").decode("utf-8", errors="ignore")

    def _convert_with_docling(self, file_path: Path) -> str:
        converter = self._get_converter()

        try:
            conversion_result = converter.convert(file_path)
            document = getattr(conversion_result, "document", None)
            if document is None:
                raise DocumentWashError(
                    f"docling conversion produced no document object for {file_path}"
                )
            markdown = document.export_to_markdown()
            if not markdown.strip():
                raise DocumentWashError(
                    f"docling conversion produced empty markdown for {file_path}"
                )
            return markdown
        except DocumentWashError:
            raise
        except Exception as exc:
            LOGGER.warning("Failed to convert document with docling: %s", file_path)
            raise DocumentWashError(
                f"Failed to convert document {file_path.name}: {exc}"
            ) from exc

    def _extract_pdf_text_fallback(self, file_path: Path) -> str:
        try:
            reader = PdfReader(str(file_path))
        except Exception as exc:
            raise DocumentWashError(
                f"pypdf could not open fallback PDF {file_path.name}: {exc}"
            ) from exc

        max_pages = self.settings.PDF_TEXT_FALLBACK_MAX_PAGES
        pages = reader.pages[:max_pages] if max_pages is not None else reader.pages
        page_texts: list[str] = []

        for page_number, page in enumerate(pages, start=1):
            try:
                text = page.extract_text() or ""
            except Exception as exc:
                LOGGER.debug(
                    "Skipping unreadable PDF page %s in %s: %s",
                    page_number,
                    file_path,
                    exc,
                )
                continue

            text = text.strip()
            if text:
                page_texts.append(f"\n\n<!-- page {page_number} -->\n\n{text}")

        markdown = "\n".join(page_texts).strip()
        if not markdown:
            raise DocumentWashError(
                f"PDF text fallback produced empty text for {file_path.name}"
            )
        return markdown

    def _convert_legacy_ppt(self, file_path: Path) -> str:
        soffice_path = shutil.which("soffice")
        if not soffice_path:
            raise UnsupportedDocumentError(
                "Legacy .ppt ingestion requires LibreOffice (`soffice`) to convert the file to .pptx before docling processing."
            )

        with tempfile.TemporaryDirectory(prefix="doctriage-ppt-") as temp_dir:
            temp_dir_path = Path(temp_dir)
            command = [
                soffice_path,
                "--headless",
                "--convert-to",
                "pptx",
                "--outdir",
                str(temp_dir_path),
                str(file_path),
            ]

            try:
                subprocess.run(
                    command,
                    check=True,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    text=True,
                )
            except subprocess.CalledProcessError as exc:
                raise DocumentWashError(
                    f"LibreOffice conversion failed for {file_path.name}: {exc.stderr.strip() or exc.stdout.strip()}"
                ) from exc

            converted_path = temp_dir_path / f"{file_path.stem}.pptx"
            if not converted_path.exists():
                raise DocumentWashError(
                    f"LibreOffice did not produce an expected PPTX for {file_path.name}"
                )

            return self._convert_with_docling(converted_path)

    def _get_converter(self):
        if self._converter is not None:
            return self._converter

        try:
            from docling.datamodel.base_models import InputFormat
            from docling.datamodel.pipeline_options import PdfPipelineOptions
            from docling.document_converter import DocumentConverter, PdfFormatOption
        except ImportError as exc:
            raise DocumentWashError(
                "docling is not installed. Install project dependencies before converting PDF or PPTX documents."
            ) from exc

        pipeline_options = PdfPipelineOptions()
        pipeline_options.do_ocr = self.settings.OCR_ENABLED
        pipeline_options.do_table_structure = True

        try:
            pipeline_options.generate_page_images = False
        except AttributeError:
            LOGGER.debug("docling PdfPipelineOptions has no generate_page_images")

        self._converter = DocumentConverter(
            allowed_formats=[
                InputFormat.PDF,
                InputFormat.PPTX,
                InputFormat.DOCX,
                InputFormat.XLSX,
                InputFormat.HTML,
                InputFormat.IMAGE,
            ],
            format_options={
                InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)
            },
        )
        return self._converter

    @classmethod
    def _looks_like_toc_entry(cls, line: str) -> bool:
        return bool(cls.TOC_ENTRY_PATTERN.match(line))

    @classmethod
    def _starts_body_content(cls, line: str) -> bool:
        if line.startswith("#"):
            return True
        if cls._looks_like_toc_entry(line):
            return False
        return len(line.split()) >= 6

    @classmethod
    def _is_navigation_fragment(cls, line: str) -> bool:
        compact = line.strip()
        if cls.PAGE_PATTERN.fullmatch(compact) or cls.SLIDE_PATTERN.fullmatch(compact):
            return True
        if re.fullmatch(r"[\d\s/|\\:_-]+", compact):
            return True
        return False

    @classmethod
    def _is_metadata_fragment(cls, line: str) -> bool:
        if cls.METADSample_PATTERN.match(line):
            return True
        if line.startswith("---") or line.startswith("***"):
            return True
        return False
