from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict

DEFAULT_CATEGORY_MAP = {
    "Architecture": "HQ/Architecture",
    "Design": "HQ/Design",
    "Implementation": "HQ/Implementation",
    "Operations": "HQ/Operations",
    "CaseStudy": "HQ/CaseStudy",
    "Research": "HQ/Research",
    "Business": "HQ/Business",
    "Thinking": "HQ/Thinking",
    "Series": "HQ/Series",
}

DEFAULT_NOISE_PATTERNS = (
    r"(?i)captured by fireshot",
    r"(?i)fire\s*shot",
    r"(?i)copyright(?:\s+|:|$)",
    r"(?i)all rights reserved",
    r"(?i)^https?://\S+$",
    r"(?i)^www\.\S+$",
    r"(?i)generated by",
)

DEFAULT_SUPPORTED_EXTENSIONS = (
    ".pdf",
    ".ppt",
    ".pptx",
    ".docx",
    ".xlsx",
    ".md",
    ".txt",
    ".html",
    ".htm",
    ".csv",
    ".png",
    ".jpg",
    ".jpeg",
    ".tif",
    ".tiff",
    ".bmp",
)


SUPPORTED_OUTPUT_LANGUAGES = {
    "auto",
    "zh-CN",
    "en",
    "ja",
    "ko",
    "de",
    "fr",
    "es",
}


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=True,
        extra="ignore",
    )

    LLM_ENDPOINT: str = Field(..., min_length=1)
    CONCURRENCY_LIMIT: int = Field(default=5, ge=1, le=64)
    SOURCE_DIR: Path = Field(...)
    OUTPUT_ROOT: Path = Field(...)

    LLM_MODEL: str | None = Field(default=None)
    LLM_API_KEY: str | None = Field(default=None)
    LLM_TIMEOUT_SECONDS: int = Field(default=90, ge=5, le=600)
    LLM_RETRY_COUNT: int = Field(default=2, ge=0, le=10)
    LLM_NUM_CTX: int | None = Field(default=8192, ge=1024, le=131072)
    MANIFEST_MAX_FILES: int = Field(default=250, ge=20, le=5000)
    SKIP_MANIFEST_ANALYSIS: bool = Field(default=True)
    DOCUMENT_SUMMARY_ENABLED: bool = Field(default=False)
    DOCUMENT_SUMMARY_MAX_CHARS: int = Field(default=600, ge=40, le=2000)
    OUTPUT_LANGUAGE: str = Field(default="auto")
    QUALITY_THRESHOLD: int = Field(default=75, ge=0, le=100)
    MAX_FILES: int | None = Field(default=None, ge=1)
    MAX_FILE_SIZE_MB: float | None = Field(default=None, gt=0)
    OCR_ENABLED: bool = Field(default=True)
    PDF_METADSample_ENABLED: bool = Field(default=False)
    PDF_TEXT_FALLBACK_ENABLED: bool = Field(default=True)
    PDF_TEXT_FALLBACK_MAX_PAGES: int | None = Field(default=300, ge=1)
    COPY_FILES: bool = Field(default=True)
    OVERWRITE_CHANGED_TARGET: bool = Field(default=True)
    REQUIRE_LOCAL_LLM: bool = Field(default=False)
    CHANGE_DETECTION_ENABLED: bool = Field(default=True)
    CHANGE_DETECTION_USE_CONTENT_HASH: bool = Field(default=False)
    FORCE_REPROCESS: bool = Field(default=False)
    RETRY_FAILED: bool = Field(default=True)
    PIPELINE_VERSION: str = Field(default="0.1.0")
    PROGRESS_ENABLED: bool = Field(default=True)
    PROGRESS_LOG_INTERVAL_SECONDS: float = Field(default=30.0, ge=1.0, le=3600.0)
    RELATIONSHIP_MINING_ENABLED: bool = Field(default=False)
    RELATIONSHIP_USE_EMBEDDINGS: bool = Field(default=False)
    RELATIONSHIP_USE_TEXT_CITATIONS: bool = Field(default=False)
    RELATIONSHIP_WORKERS: int | None = Field(default=None, ge=1, le=64)
    RELATIONSHIP_MIN_SCORE: float = Field(default=0.72, ge=0.0, le=1.0)
    RELATIONSHIP_CLUSTER_MIN_SCORE: float = Field(default=0.88, ge=0.0, le=1.0)
    RELATIONSHIP_MAX_RECORDS: int | None = Field(default=None, ge=1)
    RELATIONSHIP_MAX_CANDIDATES_PER_FILE: int = Field(default=12, ge=1, le=200)
    RELATIONSHIP_FILENAME_WINDOW: int = Field(default=8, ge=1, le=200)
    RELATIONSHIP_TIME_WINDOW: int = Field(default=8, ge=1, le=200)
    RELATIONSHIP_TIME_DECAY_DAYS: float = Field(default=30.0, gt=0.0, le=3650.0)
    RELATIONSHIP_EMBEDDING_TOP_K: int = Field(default=5, ge=1, le=100)
    RELATIONSHIP_EMBEDDING_EXHAUSTIVE_LIMIT: int = Field(default=1000, ge=2, le=20000)
    RELATIONSHIP_EMBEDDING_LLM_UNLOAD_TIMEOUT_SECONDS: float = Field(default=60.0, ge=0.0, le=3600.0)
    RELATIONSHIP_EMBEDDING_LLM_UNLOAD_POLL_SECONDS: float = Field(default=1.0, ge=0.1, le=60.0)
    EMBEDDING_ENDPOINT: str = Field(default="http://localhost:11434/api/embeddings")
    EMBEDDING_MODEL: str | None = Field(default=None)
    EMBEDDING_TIMEOUT_SECONDS: int = Field(default=120, ge=5, le=1800)
    EMBEDDING_TEXT_MAX_CHARS: int = Field(default=1200, ge=100, le=8000)
    EMBEDDING_CACHE_ENABLED: bool = Field(default=True)

    CATEGORY_MAP: dict[str, str] = Field(
        default_factory=lambda: DEFAULT_CATEGORY_MAP.copy()
    )
    NOISE_PATTERNS: tuple[str, ...] = Field(
        default_factory=lambda: DEFAULT_NOISE_PATTERNS
    )
    SUPPORTED_EXTENSIONS: tuple[str, ...] = Field(
        default=DEFAULT_SUPPORTED_EXTENSIONS
    )

    @field_validator("SOURCE_DIR", "OUTPUT_ROOT", mode="before")
    @classmethod
    def _normalize_paths(cls, value: str | Path) -> Path:
        return Path(value).expanduser().resolve()

    @field_validator("OUTPUT_LANGUAGE", mode="before")
    @classmethod
    def _normalize_output_language(cls, value: str | None) -> str:
        text = str(value or "auto").strip()
        aliases = {
            "": "auto",
            "automatic": "auto",
            "detect": "auto",
            "zh": "zh-CN",
            "zh_cn": "zh-CN",
            "zh-cn": "zh-CN",
            "cn": "zh-CN",
            "chinese": "zh-CN",
            "zh-hans": "zh-CN",
            "en-us": "en",
            "en_us": "en",
            "english": "en",
            "jp": "ja",
            "japanese": "ja",
            "kr": "ko",
            "korean": "ko",
            "german": "de",
            "french": "fr",
            "spanish": "es",
        }
        normalized = aliases.get(text.lower(), text)
        if normalized not in SUPPORTED_OUTPUT_LANGUAGES:
            supported = ", ".join(sorted(SUPPORTED_OUTPUT_LANGUAGES))
            raise ValueError(f"Unsupported OUTPUT_LANGUAGE: {value}. Use one of: {supported}")
        return normalized

    @property
    def archive_dir(self) -> Path:
        return self.OUTPUT_ROOT / "LQ_Archive"

    @property
    def state_dir(self) -> Path:
        return self.OUTPUT_ROOT / "_state"

    @property
    def processed_log_path(self) -> Path:
        return self.state_dir / "processed_files.jsonl"

    @property
    def failure_log_path(self) -> Path:
        return self.state_dir / "failed_files.jsonl"

    @property
    def progress_path(self) -> Path:
        return self.state_dir / "progress.json"

    @property
    def log_dir(self) -> Path:
        return self.OUTPUT_ROOT / "_logs"

    @property
    def application_log_path(self) -> Path:
        return self.log_dir / "doctriage.log"

    def category_dir(self, category: str) -> Path:
        return self.OUTPUT_ROOT / self.CATEGORY_MAP[category]

    @property
    def relationship_dir(self) -> Path:
        return self.OUTPUT_ROOT / "_relationships"

    @property
    def relationship_relations_path(self) -> Path:
        return self.relationship_dir / "relations.jsonl"

    @property
    def relationship_clusters_path(self) -> Path:
        return self.relationship_dir / "clusters.json"

    @property
    def embedding_cache_path(self) -> Path:
        return self.state_dir / "embedding_cache.jsonl"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
